[time]
disabled = false
style = "dimmed bold yellow"

[aws]
symbol = "󰸏 "

[azure]
symbol = " "
disabled = false
[azure.subscription_aliases]
"Zamba Cloud Sponsored Subscription" = "Zamba Cloud"
"DrivenData Paid Subscription" = "DrivenData"

[conda]
symbol = "Ⓒ "
